### ISSUE TITLE
assets

### ISSUE THREAD

**Issue by webfalter** [xsanisty/SilexStarter#7]
@silexstarter-homepage/css/bootstrap.min.css
not working in modules

search in
/public/assets/

**Comment by ikhsan017** [comment]
Hi @webfalter ,

You need to publish all asset first via the command line

`./xpress module:publish-asset`

By the way, this starter is n very early stage, and maybe there are a lot of changes will be made in near future.

**Comment by webfalter** [comment]
thx
is working :-)

**Comment by webfalter** [comment]
How do I get sql database prepared to adminlogin delivered long range?
Fatal error: Class 'SilexStarter\Migration\Migration'
